1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [1]:
import numpy as np

In [3]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [4]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [5]:
Cov1= np.mean(zp*ks)-np.mean(zp)*np.mean(ks)
Cov1

9157.839999999997

In [6]:
Cov2 = np.cov(zp,ks,ddof=0)
Cov2

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [7]:
Szp= np.std(zp)
Szp

59.115480206118605

In [8]:
Sks=np.std(ks)
Sks

174.55340157098058

In [10]:
K= Cov1/(Szp*Sks)
K

0.8874900920739158

In [11]:
K= Cov2/(Szp*Sks)
K

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

2) Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [12]:
x = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
x

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [13]:
M = x.mean()
M

118.1

In [15]:
D=x.std(ddof=1)
D

10.54566788359614

In [16]:
S= D**0.5
S

3.247409411145466

In [17]:
M-2.262*S/np.sqrt(len(x)-1)


115.65145330399632

In [20]:
M+2.262*S/np.sqrt(len(x)-1)


120.54854669600367

Доверительный интервал: 115,55; 120,55

3) Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [23]:
n=27
M=174.2
D=25
a=0.05
Ty=2.052

In [24]:
M-(Ty*D**0.5)/n**0.5


172.22546207937148

In [25]:
M+(Ty*D**0.5)/n**0.5


176.1745379206285

Доверительный интервал: 172,23;176,17